### PR TITLE
fix database #241

### PR DESCRIPTION
**Pull request by cn-kali-team**
#241 Database Views Do Not Display
https://github.com/stephenou/fruitionsite/issues/218

### CODE REVIEW

**Comment by cn-kali-team** [comment]
look at [code](https://github.com/cn-kali-team/notion-blog/blob/ce7e2d7310f229e8c74b8ae4d2878a4811d55fd0/src/lib.rs#L174-L177)

When the JavaScript file is rewritten as an HTML function, there is a title tag and JavaScript syntax error

**Comment by toksdotdev** [comment]
Thanks for the fix. Here are further improvements from my end:

**A. Light/Dark Mode Toggle**
The toggle for light/dark mode was broken. As a fix, we should add the following code snippet after this [line](https://github.com/stephenou/fruitionsite/blob/master/worker.js#L249)
```js
if (!__console.isEnabled) __console.enable();
```
        

**B. Reduce Errors in Network Tab**
Some errors still crop up in the network tab. Further improvements will be to:
- Add an `A` or `CNAME` record `exp.` that points to the domain for your notion site (can be properly documented),
- Rewrite the hostname on this [line](https://github.com/stephenou/fruitionsite/blob/master/worker.js#L87) with the function below
```js
function rewriteHostName(hostname) {
  if (hostname.startsWith("exp.")) {
    return hostname.replace(MY_DOMAIN, 'notion.so');
  }

  return 'www.notion.so';
}
```

**Comment by cn-kali-team** [comment]
> Thanks for the fix. Here are further improvements from my end:
> 
> **A. Light/Dark Mode Toggle** The toggle for light/dark mode was broken. As a fix, we should add the following code snippet after this [line](https://github.com/stephenou/fruitionsite/blob/master/worker.js#L249)
> 
> ```js
> if (!__console.isEnabled) __console.enable();
> ```
> 
> **B. Reduce Errors in Network Tab** Some errors still crop up in the network tab. Further improvements will be to:
> 
>     * Add an `A` or `CNAME` record `exp.` that points to the domain for your notion site (can be properly documented),
> 
>     * Rewrite the hostname on this [line](https://github.com/stephenou/fruitionsite/blob/master/worker.js#L87) with the function below
> 
> 
> ```js
> function rewriteHostName(hostname) {
>   if (hostname.startsWith("exp.")) {
>     return hostname.replace(MY_DOMAIN, 'notion.so');
>   }
> 
>   return 'www.notion.so';
> }
> ```

Thank you for your suggestion. In my rust [code](https://github.com/cn-kali-team/notion-blog/blob/ce7e2d7310f229e8c74b8ae4d2878a4811d55fd0/src/lib.rs#L223), I directly set up `localStorage.__console = true`;

I prefer to use the subdomain name of `notion.site`, which only requires one replacement. The disadvantage is that a variable needs to be added, such as `stephenou.notion.site` like [it code](https://github.com/cn-kali-team/notion-blog/blob/6e925e754fdb1a4659c923455306b1206bb3b55d/src/lib.rs#L20-L29)

```js
    NOTION_DOMAIN = "stephenou.notion.site"
    response = new Response(
      body
       .replace(/'${MY_DOMAIN}'/g, NOTION_DOMAIN)
```

**Comment by vipul354750** [comment]
i tried modifying my code by using this https://github.com/stephenou/fruitionsite/pull/243/files, still cant see the databases. can see red lines under page heading and description. is this due to that? can you help me out pl

**Review by ebanDev — APPROVED** [review]
Just tried it, it works like a charm :)

**Comment by seriousran** [comment]
You saved my life

**Review by chernikovalexey — COMMENTED** [review]
Fixes a very common and annoying issue on iOS and Mac devices when it blocks out the site and says "there's an issue with your iOS app, please download it from the App Store"

**Comment by Sabdvs** [comment]
Hello ! I can't do it myself 
I'm a bit of a code whiz but I'd like to be able to do it. Can anyone help me?

**Comment by Sabdvs** [comment]
I don't understand how to do it 😭

**Pull request closed without merging**
