### PR TITLE
Fix blank page issue

### PR DESCRIPTION
**Pull request by okisdev**
Fixed these issues: #113 #107 #115 #116.

* Blank Page Issue
* Message "Continue to external site by following the link below"

Please refer to [https://github.com/stephenou/fruitionsite/issues/113#issuecomment-901524424](https://github.com/stephenou/fruitionsite/issues/113#issuecomment-901524424).

### CODE REVIEW

**Comment by laughnan** [comment]
This change worked for me 🎉

**Comment by d-a-s-h-o** [comment]
Works for me too 🥳

**Comment by NChandrasekharR** [comment]
Fixed it for me too!

**Comment by pabliqe** [comment]
Can confirm this changes has solved the blank issue.

Live at https://patttterns.net/

**Comment by Creadors** [comment]
Gracias

**Comment by joshsabol46** [comment]
I'm still experiencing this as of Oct 4, 21.

Reported my issue here: https://github.com/stephenou/fruitionsite/issues/113#issuecomment-933634168

**Pull request merged**
